// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0QJMVMv9VymVMagjxI7oPzvcTcBlMqQs',
    appId: '1:386121723707:web:d576f84bfc721ccde7111e',
    messagingSenderId: '386121723707',
    projectId: 'viewkigali',
    authDomain: 'viewkigali.firebaseapp.com',
    storageBucket: 'viewkigali.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuZctw8gPVbMo8N7JtqgMKRFPFT5rd228',
    appId: '1:386121723707:android:4c816b91ec38b8bce7111e',
    messagingSenderId: '386121723707',
    projectId: 'viewkigali',
    storageBucket: 'viewkigali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCLdVSvBiqvTRTAze-Btkq-je7VIzjzqk',
    appId: '1:386121723707:ios:30722277cdee47f4e7111e',
    messagingSenderId: '386121723707',
    projectId: 'viewkigali',
    storageBucket: 'viewkigali.firebasestorage.app',
    iosBundleId: 'com.example.viewkigali',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCLdVSvBiqvTRTAze-Btkq-je7VIzjzqk',
    appId: '1:386121723707:ios:30722277cdee47f4e7111e',
    messagingSenderId: '386121723707',
    projectId: 'viewkigali',
    storageBucket: 'viewkigali.firebasestorage.app',
    iosBundleId: 'com.example.viewkigali',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0QJMVMv9VymVMagjxI7oPzvcTcBlMqQs',
    appId: '1:386121723707:web:a2448f361ed929efe7111e',
    messagingSenderId: '386121723707',
    projectId: 'viewkigali',
    authDomain: 'viewkigali.firebaseapp.com',
    storageBucket: 'viewkigali.firebasestorage.app',
  );
}
