import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // To be generated by FlutterFire CLI or provided
import 'app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Note: Firebase initialization requires firebase_options.dart
  // For now, we'll implement it such that it's ready once the user configures Firebase
  /*
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  */
  
  runApp(const ViewKigaliApp());
}

class ViewKigaliApp extends StatelessWidget {
  const ViewKigaliApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
      ),
      home: const Placeholder(),
    );
  }
}
